package dev.clawdpad.host

import android.media.midi.MidiDevice
import android.media.midi.MidiDeviceInfo
import android.media.midi.MidiManager
import android.os.Bundle
import android.view.WindowManager
import android.widget.Button
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

/**
 * clawdpad v0.1 — Clawd's wireless brain.
 *
 * Connect the Lightpad over Bluetooth first (MIDI BLE Connect app), then
 * open this. We find the bridged MIDI device, run the ROLI handshake, keep
 * the block alive with pings, and stream precomputed Clawd animation loops
 * (generated by the desktop's proven protocol stack — see
 * clawdpad/tools/make_app_stream.py).
 */
class MainActivity : AppCompatActivity() {

    private var streamer: Streamer? = null
    @Volatile private var connecting = false
    private lateinit var status: TextView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        // auto-host the moment a block appears on USB (or BLE bridge)
        val midi = getSystemService(MIDI_SERVICE) as MidiManager
        midi.registerDeviceCallback(object : MidiManager.DeviceCallback() {
            override fun onDeviceAdded(info: MidiDeviceInfo) {
                runOnUiThread { connect() }
            }
        }, android.os.Handler(mainLooper))
        // and try immediately: a bridged/attached block may already be there
        android.os.Handler(mainLooper).postDelayed({ connect() }, 800)

        val root = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(48, 96, 48, 48)
        }
        val title = TextView(this).apply {
            text = "clawdpad"
            textSize = 34f
            setTextColor(0xFFD97757.toInt())
        }
        status = TextView(this).apply {
            text = "USB: plug the block straight into this phone (best)\n" +
                   "Bluetooth: connect it in MIDI BLE Connect first\n" +
                   "…then tap Connect (auto-connects on USB plug-in)"
            textSize = 15f
            setTextColor(0xFFA89A8F.toInt())
            setPadding(0, 24, 0, 24)
        }
        root.addView(title)
        root.addView(status)

        fun btn(label: String, onTap: () -> Unit) = Button(this).apply {
            text = label
            textSize = 18f
            setOnClickListener { onTap() }
            root.addView(this)
        }

        btn("🔌 Connect to my block") { connect() }
        btn("🐾 Clawd (full size)") { streamer?.play("full") }
        btn("🐜 Chibi Clawd") { streamer?.play("mini") }
        btn("👋 Wave") { streamer?.play("wave") }
        btn("🎉 Jump!") { streamer?.play("jump") }
        btn("🔳 QR code") { streamer?.play("qr") }

        setContentView(ScrollView(this).apply { addView(root) })
    }

    private fun say(msg: String) = runOnUiThread { status.text = msg }

    private fun connect() {
        val midi = getSystemService(MIDI_SERVICE) as MidiManager
        val infos = midi.devices
        if (infos.isEmpty()) {
            say("no MIDI devices — connect the block in\nMIDI BLE Connect first, then retry")
            return
        }
        // prefer anything Lightpad-ish; otherwise first device with an input
        val info = infos.firstOrNull { name(it).contains("light", true) ||
                name(it).contains("block", true) }
            ?: infos.firstOrNull { it.inputPortCount > 0 } ?: infos[0]
        if (connecting) return                      // serialize attempts
        if (streamer?.isAlive == true) {            // already hosting: don't
            say("already streaming — buttons live") // orphan the good one
            return
        }
        connecting = true
        say("opening ${name(info)}…")
        streamer?.quit()          // release any previous (dead) port
        streamer = null
        midi.openDevice(info, { device: MidiDevice? ->
            val port = device?.openInputPort(0)
            if (port == null) {
                connecting = false
                say(if (streamer?.isAlive == true)
                    "already streaming — buttons live"
                    else "couldn't open ${name(info)} — toggle in MIDI BLE Connect; if reconnecting, power-cycle the block too")
                return@openDevice
            }
            // listen to everything the block says (topology, ACKs, faults)
            val out = device.openOutputPort(0)
            out?.connect(object : android.media.midi.MidiReceiver() {
                override fun onSend(msg: ByteArray, off: Int, len: Int, ts: Long) {
                    val hex = msg.copyOfRange(off, off + len)
                        .joinToString(" ") { "%02X".format(it) }
                    android.util.Log.i("clawdpad-rx", hex)
                }
            })
            streamer = Streamer(assets, port, ::say).also { it.start() }
            connecting = false
        }, null)
    }

    private fun name(i: MidiDeviceInfo): String =
        i.properties.getString(MidiDeviceInfo.PROPERTY_NAME) ?: "midi device"

    override fun onDestroy() {
        streamer?.quit()
        super.onDestroy()
    }
}
