package dev.clawdpad.host

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertArrayEquals
import org.junit.Test
import java.util.Base64

/**
 * Holds Protocol.kt to the golden vectors generated by the proven Python
 * stack (clawdpad/tools/make_golden_vectors.py). Passing = the Kotlin
 * port speaks bit-identical ROLI.
 */
class GoldenTest {

    private val golden = JSONObject(
        javaClass.classLoader!!.getResourceAsStream("golden.json")!!
            .readBytes().decodeToString())

    private fun b64(s: String): ByteArray = Base64.getDecoder().decode(s)

    @Test
    fun packing() {
        val cases = golden.getJSONArray("packing")
        for (c in 0 until cases.length()) {
            val case_ = cases.getJSONObject(c)
            val fields = case_.getJSONArray("fields")
            val w = BitWriter(256)
            for (f in 0 until fields.length()) {
                val pair = fields.getJSONArray(f)
                val bits = pair.getInt(1)
                if (bits > 16) w.writeBitsLong(pair.getLong(0), bits)
                else w.writeBits(pair.getInt(0), bits)
            }
            assertArrayEquals("packing case $c", b64(case_.getString("packed")),
                w.getData())
        }
    }

    @Test
    fun checksums() {
        val cases = golden.getJSONArray("checksum")
        for (c in 0 until cases.length()) {
            val case_ = cases.getJSONObject(c)
            assertEquals("checksum case $c", case_.getInt("checksum"),
                Protocol.checksum(b64(case_.getString("payload"))))
        }
    }

    @Test
    fun commands() {
        val cmds = golden.getJSONObject("commands")
        assertArrayEquals(b64(cmds.getString("ping_idx9")), PacketBuilder.ping(9))
        assertArrayEquals(b64(cmds.getString("ping_idx0")), PacketBuilder.ping(0))
        assertArrayEquals(b64(cmds.getString("topology_idx0")),
            PacketBuilder.requestTopology(0))
        assertArrayEquals(b64(cmds.getString("begin_api_idx9")),
            PacketBuilder.beginApi(9))
        assertArrayEquals(b64(cmds.getString("end_api_idx9")),
            PacketBuilder.endApi(9))
    }

    @Test
    fun bootAndTransitions() {
        val program = b64(golden.getString("program"))
        val hs = HeapStreamer(9, startIndex = 1)
        hs.setBytes(0, program)
        val boot = hs.drain()
        val goldenBoot = golden.getJSONArray("boot")
        assertEquals("boot packet count", goldenBoot.length(), boot.size)
        for (i in boot.indices)
            assertArrayEquals("boot pkt $i", b64(goldenBoot.getString(i)), boot[i])

        val transitions = golden.getJSONArray("transitions")
        for (t in 0 until transitions.length()) {
            val case_ = transitions.getJSONObject(t)
            hs.setBytes(program.size, b64(case_.getString("frame")))
            val pkts = hs.drain()
            val goldenPkts = case_.getJSONArray("packets")
            assertEquals("transition $t packet count", goldenPkts.length(), pkts.size)
            for (i in pkts.indices)
                assertArrayEquals("transition $t pkt $i",
                    b64(goldenPkts.getString(i)), pkts[i])
        }
    }
}
